# Template for this yml comes from https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml

# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - mysql:latest
  - redis:latest
  - postgres:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

Frontend:
  image: mitchellwatkins125/travelwise
  script:
    - echo "placeholder!"
    - cat makefile
    - make placeholder
    - node --version

Backend:
  image: mitchellwatkins125/travelwiseflask
  script:
    - echo "Backend Time!"
    - pip show unittest2
    - pip show Flask
    - pip show Flask-RESTful
    - pip show Flask-SQLAlchemy
    - pip show selenium
    - python Backend/Tests/FlaskUnitTests/TravelwiseBackendUnitTests.py

Postman_tests:
  image:
    name: postman/newman_alpine33
    entrypoint: [""]
  script:
    - newman --version
    - newman run Backend/Postman/postmanTests.json

Danny_Test:
  image:
    name: dtrinh403/npmt
  script:
    - npm test
