placeholder: 
	echo "I AM THE BACKEND PLACEHOLDER!"

docker:
	docker run -it --rm -v ${PWD}:/application -p 5001:5000 mitchellwatkins125/travelwiseflask

test:
	python TravelwiseBackendUnitTests.py

versions:
	pip list


