export { default as Cities } from "./Cities";
export { default as Travel } from "./Travel";
export { default as Covid } from "./Covid";
export { default as Flights } from "./Flights";
export { default as Hotels } from "./Hotels";
export { default as Dallas } from "./Dallas";
export { default as NewYork } from "./NewYork";
export { default as London } from "./London";
// export { default as SingleLegFlight } from "./SingleLegFlight";
// export { default as TwoLegFlight } from "./TwoLegFlight";
// export { default as ThreeLegFlight } from "./ThreeLegFlight";
export { default as HotelOne } from "./HotelOne";
export { default as HotelTwo } from "./HotelTwo";
export { default as HotelThree } from "./HotelThree";
export { default as CovidOne } from "./CovidOne";
export { default as CovidTwo } from "./CovidTwo";
export { default as CovidThree } from "./CovidThree";
